spring:
  application:
    name: user-subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5434/subscription_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
logging:
  level:
    root: INFO
    com.microservice.subs: DEBUG
    org.springframework: INFO
    org.hibernate: WARN